import glob
import json
import os
from typing import Dict

import numpy as np

from lib.io_utils import load_json, load_npz, save_json


def load_baseline(path: str) -> Dict[str, Dict[str, float]]:
    return load_json(path)


def compute_zscores(user_metrics: Dict[str, float], baseline: Dict[str, Dict[str, float]]) -> Dict[str, float]:
    z: Dict[str, float] = {}
    for key, val in user_metrics.items():
        if key in baseline:
            mu = float(baseline[key].get("mean", 0.0))
            sd = float(baseline[key].get("std", 1.0))
            if sd < 1e-6:
                sd = 1.0
            z[key] = (float(val) - mu) / sd
    return z


def main():
    aligned_dir = os.path.join("data", "user", "aligned")
    metrics_dir = os.path.join("data", "user", "metrics")
    os.makedirs(metrics_dir, exist_ok=True)
    # Expect exactly one aligned npz
    candidates = sorted(glob.glob(os.path.join(aligned_dir, "*.npz")))
    if not candidates:
        raise RuntimeError("No user aligned data found. Run align_and_metrics.py --split user first.")
    # Find corresponding metrics json (same base if exists) or build from aligned?
    # metrics should already be generated by align_and_metrics; fall back to reading it
    # For now, locate the latest metrics file
    metric_files = sorted(glob.glob(os.path.join(metrics_dir, "*.json")))
    if not metric_files:
        raise RuntimeError("No user metrics found. Run align_and_metrics.py --split user first.")
    user_metrics = {}
    for mf in metric_files:
        user_metrics.update(load_json(mf))
    baseline_path = os.path.join("data", "pro", "metrics", "baseline.json")
    baseline = load_baseline(baseline_path)
    z = compute_zscores(user_metrics, baseline)
    report = {
        "user_metrics": user_metrics,
        "baseline_keys": list(baseline.keys()),
        "zscores": z,
    }
    out_json = os.path.join(metrics_dir, "user_vs_baseline.json")
    save_json(report, out_json)
    print(f"User analysis saved to {out_json}")


if __name__ == "__main__":
    main()


